// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSTKlmjhGckHCltahGI_skmcnpHYS4XwU',
    appId: '1:316179015112:web:882e0b5e874e82e0d50cfd',
    messagingSenderId: '316179015112',
    projectId: 'flutter-authentication-83281',
    authDomain: 'flutter-authentication-83281.firebaseapp.com',
    storageBucket: 'flutter-authentication-83281.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpfpH3Yhmhwlfha315r_P9eO431MVWy24',
    appId: '1:316179015112:android:1089bcc715e35c02d50cfd',
    messagingSenderId: '316179015112',
    projectId: 'flutter-authentication-83281',
    storageBucket: 'flutter-authentication-83281.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1VDZvgJuex2yRdK4SDt2r2fWjZkXNaQk',
    appId: '1:316179015112:ios:63eaaf4605c3fe1bd50cfd',
    messagingSenderId: '316179015112',
    projectId: 'flutter-authentication-83281',
    storageBucket: 'flutter-authentication-83281.firebasestorage.app',
    iosBundleId: 'com.example.machineTaskAuth',
  );
}
